language: node_js
node_js:
  - '0.10'
before_script:
  - npm run-script test-cov
after_script: NODE_ENV=test YOURPACKAGE_COVERAGE=1 mocha test --require blanket --reporter mocha-lcov-reporter --recursive